# Используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - andrey@laktyushin.com
      - laktyushin@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

# Токен для https://app.codecov.io/
env:
  global:
    - CODECOV_TOKEN=845aaf21-bc98-4711-9c2f-a169e7117509